# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    build_app(
      scheme: "hypatia4ios",
      include_bitcode: true)
    upload_to_testflight
  end

  lane :tests do
    run_tests(
        devices: ["iPhone 11"],
        skip_detect_devices: false,
        scheme: "hypatia4ios")
  end


  lane :build do
    sync_code_signing(type: "appstore")
    gym(scheme: "hypatia4ios")
  end

end
